apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amumal-edge
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/kbt-practice/KBT.git
    targetRevision: main
    path: argocd/edge-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: edge-ns
  syncPolicy:
    automated: { prune: false, selfHeal: false }
