apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
        - http01:
          gatewayHTTPRoute:
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: {{ .Values.gatewayName }}
                namespace: {{ .Release.Namespace }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amumal-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - api.{{ .Values.domainBase }}
    - portainer.{{ .Values.domainBase }}
    - argocd.{{ .Values.domainBase }}