apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: edge-ns
spec:
  parentRefs:
    - name: amumal-gateway
      namespace: edge-ns
      sectionName: http
  hostnames:
    - "api.sub.amon.p-e.kr"
    - "portainer.sub.amon.p-e.kr"
    - "argocd.sub.amon.p-e.kr"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301