apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvName }}
  labels:
    app.kubernetes.io/component: portainer
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName }}
  local:
    path: {{ .Values.persistence.hostPath }}
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.nodeName }}
